### ISSUE TITLE
Implement polygon.io in Investment Pages

### ISSUE THREAD

**Issue by Phi1lS** [Phi1lS/481-Capstone#87]
Market Predictions and Investment Analytics

**Comment by abrizu** [comment]
There are a couple of bugs I need to fix, such as delocalizing the IP address for access to the backend
- For now, in backend: just change the hardcoded addresses to exp:// { xxx.xxx.x.xxx } (THIS IP ADDRESS) :8081 (whatever is on local)
   - MarketPredictionsScreen: GET and POST fetch request addresses to the same IP address
